name: weather_ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - joblib
  - pip
